import { useCallback, useEffect, useState } from 'react'

const tabs = [['overview', 'Overview'], ['security', 'Security'], ['users', 'Users'], ['suppliers', 'Suppliers'], ['refunds', 'Refunds'], ['amia', 'Amia'], ['audit', 'Audit Log']]
const supplierInitial = { companyName: '', contactName: '', email: '', phone: '', country: 'Indonesia', categoryId: '', website: '', verificationStatus: 'pending-review', reason: 'Manual supplier onboarding' }

async function api(url, options) {
  const response = await fetch(url, { credentials: 'include', ...(options || {}) })
  const payload = await response.json()
  if (!response.ok) throw new Error(payload.error?.message || 'The administrative request could not be completed.')
  return payload
}

function MetricCards({ metrics }) {
  return <section className="admin-metrics">{Object.entries(metrics).map(([key, value]) => <article key={key}><small>{key.replace(/([A-Z])/g, ' $1')}</small><strong>{value}</strong></article>)}</section>
}

function Overview({ data }) {
  if (!data) return null
  return <><MetricCards metrics={data.metrics} /><section className="admin-grid"><article className="admin-card"><h2>Platform control</h2>{Object.entries(data.platform).map(([name, rows]) => <div className="admin-platform-row" key={name}><span>{name.replace(/([A-Z])/g, ' $1')}</span><strong>{rows.length}</strong></div>)}</article><article className="admin-card"><h2>Recent administrative actions</h2>{!data.recentActions.length && <p>No administrative actions have been recorded.</p>}{data.recentActions.map((item) => <div className="admin-list-row" key={item.id}><span><strong>{item.action}</strong><small>{item.targetType} · {item.targetId}</small></span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</article></section></>
}

function Security({ data }) {
  if (!data) return null
  return <><MetricCards metrics={data.summary} /><section className="admin-card"><h2>Recent security events</h2>{!data.events.length && <p>No security events recorded.</p>}{data.events.map((event) => <div className="admin-list-row" key={event.id}><span><strong>{event.type.replaceAll('_', ' ')}</strong><small>Severity: {event.severity} {event.userId ? `· ${event.userId}` : ''}</small></span><time>{new Date(event.createdAt).toLocaleString()}</time></div>)}</section></>
}

function Users({ rows, onStatus }) {
  return <section className="admin-card"><h2>Users</h2>{rows.map((user) => <div className="admin-list-row admin-list-row--actions" key={user.userId}><span><strong>{user.name}</strong><small>{user.email} · {user.role} · {user.status}</small></span>{user.role !== 'administrator' && <button type="button" onClick={() => onStatus(user)}>{user.status === 'suspended' ? 'Restore' : 'Suspend'}</button>}</div>)}</section>
}

function Suppliers({ rows, categories, form, setForm, onCreate, onStatus, saving }) {
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })) }
  return <div className="admin-grid admin-grid--suppliers"><form className="admin-card admin-form" onSubmit={onCreate}><h2>Add Supplier</h2><label>Business name<input required value={form.companyName} onChange={(event) => update('companyName', event.target.value)} /></label><label>Contact name<input required value={form.contactName} onChange={(event) => update('contactName', event.target.value)} /></label><label>Email<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} /></label><label>Phone<input required value={form.phone} onChange={(event) => update('phone', event.target.value)} /></label><label>Country<input required value={form.country} onChange={(event) => update('country', event.target.value)} /></label><label>Category<select required value={form.categoryId} onChange={(event) => update('categoryId', event.target.value)}><option value="">Select a category</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Website<input type="url" value={form.website} onChange={(event) => update('website', event.target.value)} /></label><label>Initial verification<select value={form.verificationStatus} onChange={(event) => update('verificationStatus', event.target.value)}><option value="pending-review">Pending review</option><option value="approved">Approved</option></select></label><label className="wide">Administrative reason<textarea required minLength="5" value={form.reason} onChange={(event) => update('reason', event.target.value)} /></label><button className="btn btn-charcoal wide" disabled={saving}>{saving ? 'Creating…' : 'Add Supplier'}</button></form><section className="admin-card"><h2>Supplier directory</h2>{rows.map((supplier) => <div className="admin-list-row admin-list-row--supplier" key={supplier.id}><span><strong>{supplier.displayName}</strong><small>{supplier.email} · {supplier.country} · {supplier.verificationStatus}</small></span><select value={supplier.verificationStatus} onChange={(event) => onStatus(supplier, event.target.value)}><option value="pending-review">Pending review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select></div>)}</section></div>
}

function Refunds({ data, form, setForm, onSubmit, saving }) {
  if (!data) return null
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })) }
  const selected = data.orders.find((item) => item.id === form.orderId)
  return <div className="admin-grid"><form className="admin-card admin-form" onSubmit={onSubmit}><h2>Request a refund</h2><p className="admin-warning">Payment provider not configured. This records an administrative request but does not move money.</p><label className="wide">Eligible order<select required value={form.orderId} onChange={(event) => update('orderId', event.target.value)}><option value="">Select an order</option>{data.orders.map((order) => <option value={order.id} disabled={order.refundableAmount < 1} key={order.id}>{order.orderNumber} · {order.refundableAmount} {order.currency} refundable</option>)}</select></label><label>Amount<input required type="number" min="1" max={selected?.refundableAmount || undefined} value={form.amount} onChange={(event) => update('amount', event.target.value)} /></label><label className="wide">Reason<textarea required minLength="10" value={form.reason} onChange={(event) => update('reason', event.target.value)} /></label><label className="admin-confirm wide"><input type="checkbox" checked={form.confirmed} onChange={(event) => update('confirmed', event.target.checked)} />I confirm the order and refundable amount have been reviewed.</label><button className="btn btn-charcoal wide" disabled={saving || !form.confirmed}>{saving ? 'Recording…' : 'Record refund request'}</button></form><section className="admin-card"><h2>Refund activity</h2>{!data.refunds.length && <p>No refund requests recorded.</p>}{data.refunds.map((refund) => <div className="admin-list-row" key={refund.id}><span><strong>{refund.orderNumber} · {refund.amount} {refund.currency}</strong><small>{refund.status.replaceAll('_', ' ')} · no provider execution</small></span><time>{new Date(refund.createdAt).toLocaleString()}</time></div>)}</section></div>
}

function Amia({ data, onSave, saving }) {
  const [form, setForm] = useState(null)
  useEffect(() => { if (data) setForm({ enabled: data.settings.enabled, moderation: data.settings.moderation, capabilities: data.settings.capabilities, reason: 'Controlled Amia configuration update' }) }, [data])
  if (!data || !form) return null
  function toggle(capability) { setForm((current) => ({ ...current, capabilities: current.capabilities.includes(capability) ? current.capabilities.filter((item) => item !== capability) : [...current.capabilities, capability] })) }
  return <div className="admin-grid"><form className="admin-card admin-form" onSubmit={(event) => { event.preventDefault(); onSave(form) }}><h2>Amia controls</h2><label>Service status<select value={form.enabled ? 'enabled' : 'disabled'} onChange={(event) => setForm((current) => ({ ...current, enabled: event.target.value === 'enabled' }))}><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select></label><label>Moderation<select value={form.moderation} onChange={(event) => setForm((current) => ({ ...current, moderation: event.target.value }))}><option value="standard">Standard</option><option value="strict">Strict</option></select></label><fieldset className="wide"><legend>Enabled capabilities</legend>{['products', 'suppliers', 'services', 'categories', 'auctions', 'flash-sales'].map((item) => <label key={item}><input type="checkbox" checked={form.capabilities.includes(item)} onChange={() => toggle(item)} />{item}</label>)}</fieldset><label className="wide">Administrative reason<textarea required minLength="5" value={form.reason} onChange={(event) => setForm((current) => ({ ...current, reason: event.target.value }))} /></label><button className="btn btn-charcoal wide" disabled={saving}>{saving ? 'Saving…' : 'Save controlled configuration'}</button></form><section className="admin-card"><h2>Amia status</h2><div className="admin-platform-row"><span>Status</span><strong>{data.status}</strong></div><div className="admin-platform-row"><span>Provider configuration</span><strong>{data.provider.configured ? 'Configured' : 'Missing'}</strong></div><div className="admin-platform-row"><span>Secret exposure</span><strong>{data.provider.secretExposed ? 'Unsafe' : 'Protected'}</strong></div><MetricCards metrics={data.usage} /></section></div>
}

function Audit({ rows }) {
  return <section className="admin-card"><h2>Administrative audit log</h2>{!rows.length && <p>No actions recorded.</p>}{rows.map((item) => <div className="admin-list-row" key={item.id}><span><strong>{item.action}</strong><small>{item.administratorEmail} · {item.targetType} · {item.targetId}{item.reason ? ` · ${item.reason}` : ''}</small></span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</section>
}

export default function AdminPage() {
  const [tab, setTab] = useState('overview'); const [data, setData] = useState(null); const [categories, setCategories] = useState([]); const [supplierForm, setSupplierForm] = useState(supplierInitial); const [refundForm, setRefundForm] = useState({ orderId: '', amount: '', reason: '', confirmed: false }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const endpoint = { overview: '/api/admin/dashboard', security: '/api/admin/security', users: '/api/admin/users?limit=100', suppliers: '/api/admin/suppliers?limit=100', refunds: '/api/admin/refunds', amia: '/api/admin/amia', audit: '/api/admin/audit-log?limit=100' }[tab]
  const load = useCallback(async () => { setLoading(true); setMessage(''); try { const payload = await api(endpoint); setData(payload.data); if (tab === 'suppliers' && !categories.length) { const categoryPayload = await api('/api/categories?limit=100'); setCategories(categoryPayload.data) } } catch (error) { setData(null); setMessage(error.message) } finally { setLoading(false) } }, [categories.length, endpoint, tab])
  useEffect(() => { load() }, [load])
  async function mutate(url, options) { setSaving(true); setMessage(''); try { await api(url, options); setMessage('Administrative action recorded.'); await load() } catch (error) { setMessage(error.message) } finally { setSaving(false) } }
  async function userStatus(user) { const status = user.status === 'suspended' ? 'active' : 'suspended'; const reason = window.prompt(`Reason to ${status === 'suspended' ? 'suspend' : 'restore'} this account:`); if (!reason) return; await mutate(`/api/admin/users/${user.userId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, reason }) }) }
  async function supplierStatus(supplier, status) { const reason = window.prompt(`Reason for changing supplier status to ${status}:`); if (!reason) return; await mutate(`/api/admin/suppliers/${supplier.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, reason }) }) }
  async function createSupplier(event) { event.preventDefault(); await mutate('/api/admin/suppliers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(supplierForm) }); setSupplierForm(supplierInitial) }
  async function createRefund(event) { event.preventDefault(); await mutate('/api/admin/refunds', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...refundForm, amount: Number(refundForm.amount) }) }); setRefundForm({ orderId: '', amount: '', reason: '', confirmed: false }) }
  async function saveAmia(form) { await mutate('/api/admin/amia', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }) }
  const rows = Array.isArray(data) ? data : []
  return <main className="admin-page"><aside className="admin-nav"><a className="logo" href="/">buyamia</a><p>Main Admin Panel</p><nav>{tabs.map(([id, label]) => <button className={tab === id ? 'active' : ''} type="button" onClick={() => setTab(id)} key={id}>{label}<span>›</span></button>)}</nav><a href="/">Return to Buyamia</a></aside><section className="admin-main"><header><div><p className="eyebrow">Authorized administration</p><h1>{tabs.find(([id]) => id === tab)?.[1]}</h1></div><span>Protected control center</span></header>{message && <p className={`admin-message${message === 'Administrative action recorded.' ? ' is-success' : ''}`} role="status">{message}</p>}{loading && <p className="admin-state">Loading administrative data…</p>}{!loading && !message && tab === 'overview' && <Overview data={data} />}{!loading && tab === 'security' && <Security data={data} />}{!loading && tab === 'users' && <Users rows={rows} onStatus={userStatus} />}{!loading && tab === 'suppliers' && <Suppliers rows={rows} categories={categories} form={supplierForm} setForm={setSupplierForm} onCreate={createSupplier} onStatus={supplierStatus} saving={saving} />}{!loading && tab === 'refunds' && <Refunds data={data} form={refundForm} setForm={setRefundForm} onSubmit={createRefund} saving={saving} />}{!loading && tab === 'amia' && <Amia data={data} onSave={saveAmia} saving={saving} />}{!loading && tab === 'audit' && <Audit rows={rows} />}</section></main>
}
