import { useEffect, useState } from 'react'

function money(value, currency) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: currency || 'IDR', maximumFractionDigits: 0 }).format(value || 0) }

export default function AffiliatePage() {
  const [dashboard, setDashboard] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  async function load() { setLoading(true); setMessage(''); try { const response = await fetch('/api/account/affiliate'); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load affiliate information.'); setDashboard(payload.data) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function copyLink() { try { const response = await fetch('/api/account/affiliate/link', { method: 'POST' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to generate your referral link.'); const url = new URL(payload.data.referralUrl, window.location.origin).href; await navigator.clipboard.writeText(url); setMessage('Referral link copied.') } catch (error) { setMessage(error.message || 'Unable to copy your referral link.') } }
  const stats = dashboard?.statistics
  return <main className="affiliate-page shell"><header className="affiliate-page__head"><p className="eyebrow">My Account</p><h1>Affiliate <em>Program</em></h1><p>Share Buyamia and earn rewards for successful referrals.</p></header>{loading && <p className="history-state">Loading affiliate dashboard…</p>}{!loading && message && <p className={`history-state${message === 'Referral link copied.' ? '' : ' history-state--error'}`}>{message}</p>}{!loading && dashboard && <><section className="affiliate-link"><div><small>Your referral link</small><strong>{new URL(dashboard.profile.referralUrl, window.location.origin).href}</strong><em>{dashboard.profile.status}</em></div><button type="button" className="btn btn-charcoal" onClick={copyLink}>Copy link</button></section><section className="affiliate-stats"><article><small>Total referrals</small><strong>{stats.totalReferrals}</strong></article><article><small>Successful referrals</small><strong>{stats.successfulReferrals}</strong></article><article><small>Pending earnings</small><strong>{money(stats.pendingEarnings, stats.currency)}</strong></article><article><small>Total earnings</small><strong>{money(stats.totalEarnings, stats.currency)}</strong></article></section><section className="affiliate-history"><h2>Commission history</h2>{!dashboard.commissions.length && <p>No commissions yet. Your referral activity will appear here.</p>}{dashboard.commissions.map((commission) => <article key={commission.id}><span><strong>{commission.description || 'Referral commission'}</strong><small>{new Date(commission.createdAt).toLocaleDateString()} · {commission.status}</small></span><b>{money(commission.amount, stats.currency)}</b></article>)}</section><section className="affiliate-history"><h2>Referral history</h2>{!dashboard.referrals.length && <p>No referrals yet. Share your link to get started.</p>}{dashboard.referrals.map((referral) => <article key={referral.id}><span><strong>{referral.name || referral.email || 'Referral'}</strong><small>{new Date(referral.createdAt).toLocaleDateString()} · {referral.status}</small></span></article>)}</section></>}</main>
}
