import { useEffect, useState } from 'react'

function price(product) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: product.currency || 'IDR', maximumFractionDigits: 0 }).format(product.price || 0) }
function openWithKeyboard(event, url) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); window.location.href = url } }

export default function BrandsPage() {
  const detailId = window.location.pathname.match(/^\/brands\/([^/]+)$/)?.[1]
  const [brands, setBrands] = useState([]); const [categories, setCategories] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const [detail, setDetail] = useState(null)
  useEffect(() => { const controller = new AbortController(); fetch('/api/categories?limit=100', { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load filters.'); setCategories(payload.data || []) }).catch((error) => { if (error.name !== 'AbortError') setMessage(error.message) }); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); setMessage(''); try { if (detailId) { const response = await fetch(`/api/brands/${encodeURIComponent(detailId)}`, { signal: controller.signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load brand.'); setDetail(payload.data); return } const params = new URLSearchParams({ limit: '100', sort: 'name' }); if (query.trim()) params.set('q', query.trim()); if (category) params.set('category', category); const response = await fetch(`/api/brands?${params}`, { signal: controller.signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load brands.'); setBrands(payload.data) } catch (error) { if (error.name !== 'AbortError') setMessage(error.message) } finally { setLoading(false) } }, 180); return () => { controller.abort(); window.clearTimeout(timer) } }, [query, category, detailId])
  if (detailId) return <main className="brands-page"><div className="brand-breadcrumb shell"><a href="/brands">Brands</a> <span>›</span> {detail?.name || 'Brand'}</div>{loading && <p className="brands-state">Loading brand…</p>}{!loading && message && <p className="brands-state brands-state--error">{message}</p>}{!loading && detail && <section className="brands-directory shell"><header><h1>{detail.name}</h1><p>{detail.description}</p></header><div className="brand-featured-grid"><article className="brand-featured-card"><header><img src={detail.logo} alt="" /><span><strong>{detail.name}</strong><small>{detail.country}</small></span>{detail.verified && <em>Verified</em>}</header><div>{detail.products.map((product) => <a href={`/products/${product.id}`} key={product.id}><img src={product.image} alt={product.title} /><small>{product.title}</small><b>{price(product)}</b></a>)}</div><footer role="link" tabIndex="0" onKeyDown={(event) => openWithKeyboard(event, `/categories?category=${detail.categoryId}`)} onClick={() => { window.location.href = `/categories?category=${detail.categoryId}` }}>Shop more from this seller <span>↗</span></footer></article></div></section>}</main>
  const featured = brands.filter((brand) => brand.featured); const groups = brands.reduce((result, brand) => { const letter = brand.name[0].toUpperCase(); (result[letter] ||= []).push(brand); return result }, {})
  return <main className="brands-page"><div className="brand-breadcrumb shell">Home <span>›</span> Brands</div><div className="brands-create-entry shell"><span>Don&apos;t have a brand?</span><a className="btn btn-charcoal" href="/brands/create">Create a brand</a></div><section className="brands-featured"><div className="shell"><p className="eyebrow">Featured brands</p><header><h1>Artisan craft. Enterprise<br /><em>capability.</em></h1><p>Whether you&apos;re sourcing a single statement piece or filling a hotel contract across multiple properties, our featured brands have the production capacity, quality standards, and logistics experience to match your requirements.</p></header>{loading && <p className="brands-state">Loading brands…</p>}{!loading && message && <p className="brands-state brands-state--error">{message}</p>}{!loading && !message && <div className="brand-featured-grid">{featured.map((brand) => <article className="brand-featured-card" key={brand.id}><header><img src={brand.logo} alt="" /><span><strong>{brand.name}</strong><small>{brand.country}</small></span>{brand.verified && <em>Verified</em>}</header><div>{brand.products.slice(0, 3).map((product) => <a href={`/products/${product.id}`} key={product.id}><img src={product.image} alt={product.title} /><small>{product.title}</small><b>{price(product)}</b></a>)}</div><footer role="link" tabIndex="0" onKeyDown={(event) => openWithKeyboard(event, `/brands/${brand.id}`)} onClick={() => { window.location.href = `/brands/${brand.id}` }}>Shop more from this seller <span>↗</span></footer></article>)}</div>}</div></section><section className="brands-directory shell"><nav aria-label="Brand index">{'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((letter) => <button type="button" key={letter} disabled={!groups[letter]} onClick={() => document.getElementById(`brand-${letter}`)?.scrollIntoView({ behavior: 'smooth' })}>{letter}</button>)}</nav><div className="brands-controls"><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All filters</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><label><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Brands" /></label></div>{!loading && !message && !brands.length && <p className="brands-state">No brands found.</p>}{!loading && !message && Object.entries(groups).map(([letter, entries]) => <section className="brand-letter" id={`brand-${letter}`} key={letter}><h2>{letter}</h2><div>{entries.map((brand) => <article key={brand.id}><a href={`/brands/${brand.id}`}>{brand.name}</a><small>{brand.country} · {brand.productCount} products</small></article>)}</div></section>)}</section></main>
}
