import { useEffect, useState } from 'react'

function money(value, currency) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: currency || 'IDR', maximumFractionDigits: 0 }).format(value || 0) }

export default function CategoriesPage() {
  const [categories, setCategories] = useState([]); const [selected, setSelected] = useState(null); const [products, setProducts] = useState([]); const [meta, setMeta] = useState(null); const [sort, setSort] = useState('featured'); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  useEffect(() => { fetch('/api/categories?limit=100').then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load categories.'); setCategories(payload.data); const furniture = payload.data.find((item) => item.slug === 'furniture') || payload.data[0]; setSelected(furniture || null) }).catch((error) => { setMessage(error.message); setLoading(false) }) }, [])
  useEffect(() => { if (!selected) return; setLoading(true); setMessage(''); fetch(`/api/categories/${encodeURIComponent(selected.id)}/products?limit=24&sort=${sort}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load category products.'); setProducts(payload.data); setMeta(payload.meta) }).catch((error) => setMessage(error.message)).finally(() => setLoading(false)) }, [selected, sort])
  return <main className="categories-page"><div className="category-breadcrumb shell">Home <span>›</span> {selected?.name || 'Categories'}</div><section className="category-hero shell"><img src="/assets/category-bg.png" alt="" /><h1>Wholesale <em>{selected?.name || 'Categories'}</em></h1></section><section className="category-intro shell"><p>Quality pieces built to last, priced for volume. Browse commercial-grade products that hold up in high-traffic spaces without the markup.</p></section><section className="category-catalog shell"><div className="category-toolbar"><div className="category-tabs">{categories.map((category) => <button type="button" className={category.id === selected?.id ? 'is-active' : ''} onClick={() => setSelected(category)} key={category.id}>{category.name}</button>)}</div><label>Sort by <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Featured</option><option value="sold">Popular</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></label></div>{loading && <p className="category-state">Loading products…</p>}{!loading && message && <p className="category-state category-state--error">{message}</p>}{!loading && !message && <><p className="category-count">{meta?.total || 0} items</p>{!products.length ? <p className="category-state">No products found in this category.</p> : <div className="category-product-grid">{products.map((product) => <article className="category-product-card" key={product.id}><a href={`/products/${product.id}`}><img src={product.image} alt={product.title} /><h2>{product.title}</h2><small>Estimated price</small><strong>{money(product.price, product.currency)}</strong><footer><span>{selected?.name}</span><span>★ {product.rating}/5</span></footer></a></article>)}</div>}</>}</section></main>
}
