import { useMemo, useState } from 'react'

const authHeaders = { 'Content-Type': 'application/json' }
const initialForm = { productName: '', preferredSupplier: '', orderQuantity: '', frequency: 'weekly', minimumBusinesses: '10', maximumBusinesses: '20', targetVolume: '', location: 'Bali, Indonesia', matchingRadius: 'city', industryMatching: 'same-industry', poolWindowDays: '14', monitoring: '' }
function requestAuth() { window.dispatchEvent(new CustomEvent('buyamia:auth-required', { detail: { mode: 'login' } })) }

async function createPool(data, publish) {
  const response = await fetch('/api/buying-pools', { method: 'POST', credentials: 'include', headers: authHeaders, body: JSON.stringify({ ...data, orderQuantity: Number(data.orderQuantity), minimumBusinesses: Number(data.minimumBusinesses), maximumBusinesses: data.maximumBusinesses ? Number(data.maximumBusinesses) : null, targetVolume: Number(data.targetVolume), poolWindowDays: Number(data.poolWindowDays), publish }) })
  const payload = await response.json()
  if (!response.ok) throw new Error(payload.error?.message || 'Unable to save this Buying Pool.')
  return payload.data
}

function Choice({ active, children, onClick }) { return <button className={active ? 'active' : ''} type="button" onClick={onClick}>{children}</button> }
function Field({ label, children }) { return <label><span>{label}</span>{children}</label> }

export default function CreateBuyingPoolPage() {
  const [step, setStep] = useState(1); const [form, setForm] = useState(initialForm); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [launched, setLaunched] = useState(null)
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  const visibleSteps = useMemo(() => step <= 3 ? [1, 2, 3] : step === 4 ? [2, 3, 4] : [4, 5], [step])
  const continueFrom = (event, next) => { event.preventDefault(); if (!event.currentTarget.reportValidity()) return; setStep(next) }
  const save = async (publish) => { setBusy(true); setMessage(''); try { const pool = await createPool(form, publish); if (publish) setLaunched(pool); else { setMessage('Buying Pool saved as draft.'); setTimeout(() => window.location.assign('/buying-pools'), 700) } } catch (error) { if (error.message.includes('Sign in')) requestAuth(); setMessage(error.message) } finally { setBusy(false) } }
  const summary = <ul><li>Product / Category <strong>{form.productName || '[Entry]'}</strong></li><li>Quantity needed <strong>{form.orderQuantity || '[Entry]'}</strong></li><li>Order frequency <strong>{form.frequency}</strong></li><li>Minimum to activate <strong>{form.minimumBusinesses || '[X businesses]'}</strong></li><li>Maximum pool size <strong>{form.maximumBusinesses ? `${form.maximumBusinesses} businesses` : 'No limit'}</strong></li><li>Matching radius <strong>{form.matchingRadius}</strong></li><li>Industry matching <strong>{form.industryMatching}</strong></li><li>Pool window <strong>{form.poolWindowDays} days</strong></li><li>Amia monitoring <strong>{form.monitoring || 'Not set up'}</strong></li></ul>
  if (launched) return <main className="pool-builder-page"><div className="category-breadcrumb shell">Home <span>›</span> Buying Pools</div><header><p className="eyebrow">Start a Buying Pool</p><h1>Tell us what you need.</h1></header><section className="pool-launch shell"><aside><p className="eyebrow">Step 5</p><h2>Pool Details</h2>{summary}<div className="pool-disclaimer">Buying pools unlock savings based on combined order volume across verified businesses.</div><div><button disabled>Save as Draft</button><button disabled>Launch Pool</button></div></aside><article style={{ backgroundImage: "linear-gradient(rgba(52,83,9,.75),rgba(52,83,9,.75)),url('/assets/carved-bg.png')" }}><div><p>Your pool is live.</p><h2>Amia is now matching your pool with nearby businesses ordering similar products. You’ll be notified the moment someone joins.</h2></div><footer><a href={`/buying-pools/${launched.id}`}>View Pool Status</a><a href="/buying-pools/create">Start another Pool</a></footer></article></section></main>
  const cards = {
    1: <form onSubmit={(event) => continueFrom(event, 2)}><p className="eyebrow">Step 1</p><h2>What Are You<br />Ordering?</h2><small>*Required Fields</small><Field label="Product or Category *"><input required value={form.productName} onChange={(event) => update('productName', event.target.value)} placeholder="Cleaning supplies" /></Field><Field label="Preferred supplier or brand"><input value={form.preferredSupplier} onChange={(event) => update('preferredSupplier', event.target.value)} placeholder="Optional - Amia can suggest if left blank" /></Field><Field label="Order quantity you typically need"><input required type="number" min="1" value={form.orderQuantity} onChange={(event) => update('orderQuantity', event.target.value)} placeholder="10 units" /></Field><Field label="Order frequency"><div className="pool-builder-choices"><Choice active={form.frequency === 'weekly'} onClick={() => update('frequency', 'weekly')}>Weekly</Choice><Choice active={form.frequency === 'monthly'} onClick={() => update('frequency', 'monthly')}>Monthly</Choice><Choice active={form.frequency === 'quarterly'} onClick={() => update('frequency', 'quarterly')}>Quarterly</Choice></div></Field><button className="pool-builder-next">Save &amp; Continue</button></form>,
    2: <form onSubmit={(event) => continueFrom(event, 3)}><p className="eyebrow">Step 2</p><h2>Set Your Pool’s Terms</h2><p>Define what it takes to unlock savings.</p><small>*Required Fields</small><Field label="Minimum businesses to activate savings *"><input required type="number" min="2" value={form.minimumBusinesses} onChange={(event) => update('minimumBusinesses', event.target.value)} /></Field><Field label="Maximum pool size (optional)"><input type="number" min={form.minimumBusinesses} value={form.maximumBusinesses} onChange={(event) => update('maximumBusinesses', event.target.value)} /></Field><Field label="Target order volume"><input required type="number" min="1" value={form.targetVolume} onChange={(event) => update('targetVolume', event.target.value)} placeholder="200 units" /></Field><button className="pool-builder-next">Save &amp; Continue</button></form>,
    3: <form onSubmit={(event) => continueFrom(event, 4)}><p className="eyebrow">Step 3</p><h2>Location &amp; Matching</h2><p>Where should Amia look for participants?</p><small>*Required Fields</small><Field label="Your business location"><input required value={form.location} onChange={(event) => update('location', event.target.value)} /></Field><Field label="Matching radius"><div className="pool-builder-choices"><Choice active={form.matchingRadius === 'neighborhood'} onClick={() => update('matchingRadius', 'neighborhood')}>Same neighborhood</Choice><Choice active={form.matchingRadius === 'city'} onClick={() => update('matchingRadius', 'city')}>Same city</Choice><Choice active={form.matchingRadius === 'unlimited'} onClick={() => update('matchingRadius', 'unlimited')}>No limit</Choice></div></Field><Field label="Industry matching"><div className="pool-builder-choices vertical"><Choice active={form.industryMatching === 'same-industry'} onClick={() => update('industryMatching', 'same-industry')}>Only businesses in my industry</Choice><Choice active={form.industryMatching === 'compatible'} onClick={() => update('industryMatching', 'compatible')}>Any compatible business</Choice></div></Field><button className="pool-builder-next">Save &amp; Continue</button></form>,
    4: <form onSubmit={(event) => continueFrom(event, 5)}><p className="eyebrow">Step 4</p><h2>Pool Duration &amp;<br />Notifications</h2><p>How long should this pool stay open?</p><small>*Required Fields</small><Field label="Pool window"><div className="pool-builder-choices"><Choice active={form.poolWindowDays === '7'} onClick={() => update('poolWindowDays', '7')}>7 days</Choice><Choice active={form.poolWindowDays === '14'} onClick={() => update('poolWindowDays', '14')}>14 days</Choice><Choice active={form.poolWindowDays === '30'} onClick={() => update('poolWindowDays', '30')}>30 days</Choice></div></Field><Field label="Amia monitoring"><textarea value={form.monitoring} onChange={(event) => update('monitoring', event.target.value)} placeholder="Notify me as businesses join this pool on WhatsApp / Telegram" /></Field><button className="pool-builder-next">Save &amp; Review Details</button></form>,
    5: <section className="pool-builder-summary"><p className="eyebrow">Step 5</p><h2>Pool Details</h2><button className="pool-builder-edit" onClick={() => setStep(1)}>Edit</button>{summary}<div className="pool-disclaimer">Buying pools unlock savings based on combined order volume across verified businesses. Final pricing is confirmed once the pool reaches its minimum threshold.</div><footer><button disabled={busy} onClick={() => save(false)}>Save as Draft</button><button className="btn btn-charcoal" disabled={busy} onClick={() => save(true)}>Launch Pool</button></footer></section>,
  }
  return <main className="pool-builder-page"><div className="category-breadcrumb shell">Home <span>›</span> Buying Pools</div><header><p className="eyebrow">Start a Buying Pool</p><h1>Tell us what you need.</h1></header><section className={`pool-builder-track shell columns-${visibleSteps.length}`}>{visibleSteps.map((number) => <article className={number === step ? 'active' : ''} key={number}>{cards[number]}</article>)}</section><nav className="pool-builder-nav shell"><button disabled={step === 1} onClick={() => setStep((current) => Math.max(1, current - 1))}>←</button><div><span style={{ width: `${step * 20}%` }} /></div><button disabled={step === 5} onClick={() => setStep((current) => Math.min(5, current + 1))}>→</button></nav>{message && <p className="pool-builder-message">{message}</p>}</main>
}
