import { useEffect, useState } from 'react'

const supplierHeaders = { 'Content-Type': 'application/json', 'X-User-Id': 'seller-demo-user', 'X-User-Name': 'Sari Living' }
async function api(url, options = {}) { const response = await fetch(url, options); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to create this category.'); return payload }

export default function CreateCategoryPage() {
  const [categories, setCategories] = useState([]); const [form, setForm] = useState({ name: '', description: '', parentCategoryId: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { api('/api/categories?limit=100').then((payload) => setCategories(payload.data)).catch((error) => setMessage(error.message)).finally(() => setLoading(false)) }, [])
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(''); try { const { data } = await api('/api/categories', { method: 'POST', headers: supplierHeaders, body: JSON.stringify(form) }); setMessage('Category created successfully.'); setTimeout(() => window.location.assign(`/categories?category=${encodeURIComponent(data.slug)}`), 500) } catch (error) { setMessage(error.message) } finally { setSaving(false) } }
  return <main className="categories-page create-category-page"><div className="category-breadcrumb shell"><a href="/categories">Categories</a><span>›</span>Create Category</div><section className="category-create-hero shell"><p className="eyebrow">Supplier categories</p><h1>Create Category</h1><p>Add a category to Buyamia&apos;s existing product directory.</p></section><section className="category-create-form shell">{loading && <p className="category-state">Loading categories…</p>}{!loading && <form onSubmit={submit}><label>Category name<input required minLength="2" maxLength="80" value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Category name" /></label><label>Description<textarea maxLength="500" value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Describe the products visitors will find here." /></label><label>Parent category <small>Optional</small><select value={form.parentCategoryId} onChange={(event) => update('parentCategoryId', event.target.value)}><option value="">No parent category</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><div className="category-create-actions"><a href="/categories">Cancel</a><button className="btn btn-charcoal" disabled={saving} type="submit">{saving ? 'Creating…' : 'Create Category'}</button></div>{message && <p className="category-create-message" role="status">{message}</p>}</form>}</section></main>
}
