import { useEffect, useState } from 'react'

const money = (value, currency = 'IDR') => new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value)
const sold = (value) => new Intl.NumberFormat('en', { notation: value >= 1000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value)
const api = async (url) => { const response = await fetch(url); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load fast-selling products.'); return payload }

function FastFooter() { return <footer className="account-footer fast-footer shell"><div className="logo">buyamia</div><p>Buy some comfort. Buy<br />some care.</p><div><small>SHOP</small><span>All Products</span><span>Furniture</span><span>Home Decor</span></div><div><small>ABOUT US</small><span>About Us</span><span>Sustainability</span><span>Sell on Buyamia</span></div><div><small>SUPPORT</small><span>Help Center</span><span>Contact Us</span><span>FAQ</span></div></footer> }

function FastCard({ product }) {
  return <article className="category-product-card fast-card"><a href={`/fast-selling/${product.id}`}><div><img src={product.image} alt={product.title} />{product.verificationBadge && <em>✓</em>}</div><h2>{product.title}</h2><small>{product.seller?.name || product.category?.name}</small><span>{product.originalPrice && <del>{money(product.originalPrice, product.currency)}</del>}<strong>{money(product.currentPrice, product.currency)}</strong></span><footer><b>{sold(product.soldCount)} sold</b><span>★ {product.rating}/5 · {product.reviewCount}</span></footer></a></article>
}

function FastDetail({ id }) {
  const [product, setProduct] = useState(null); const [message, setMessage] = useState('')
  useEffect(() => { api(`/api/fast-selling/${encodeURIComponent(id)}`).then((payload) => setProduct(payload.data)).catch((error) => setMessage(error.message)) }, [id])
  if (!product) return <main className={`fast-state shell${message ? ' fast-state--error' : ''}`}>{message || 'Loading product…'}</main>
  return <><main className="fast-detail shell"><div className="category-breadcrumb"><a href="/fast-selling">Fast Selling</a> <span>›</span> {product.title}</div><div><section><img src={product.images[0]} alt={product.title} /></section><section><p className="eyebrow">{product.verificationBadge || 'Popular on Buyamia'}</p><h1>{product.title}</h1><p>{product.description}</p><div className="fast-detail__price">{product.originalPrice && <del>{money(product.originalPrice, product.currency)}</del>}<strong>{money(product.currentPrice, product.currency)}</strong></div><dl><div><dt>Seller</dt><dd>{product.seller?.name || 'Buyamia marketplace'}</dd></div><div><dt>Category</dt><dd>{product.category?.name}</dd></div><div><dt>Availability</dt><dd>{product.availability ? `${product.stock} in stock` : 'Unavailable'}</dd></div><div><dt>Sold</dt><dd>{sold(product.soldCount)}</dd></div><div><dt>Reviews</dt><dd>★ {product.rating}/5 · {product.reviewCount}</dd></div></dl><a className="btn btn-accent" href={`/cart?product=${encodeURIComponent(product.id)}`}>Add to cart</a></section></div></main><FastFooter /></>
}

export default function FastSellingPage() {
  const detailId = window.location.pathname.match(/^\/fast-selling\/([^/]+)$/)?.[1]
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [sellers, setSellers] = useState([]); const [meta, setMeta] = useState({ page: 1, pages: 1, total: 0 }); const [filters, setFilters] = useState({ q: '', category: '', seller: '', minPrice: '', maxPrice: '', sort: 'sales-volume', page: 1 }); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  useEffect(() => { if (detailId) return; const timer = setTimeout(async () => { setLoading(true); setMessage(''); const query = new URLSearchParams({ sort: filters.sort, page: String(filters.page), limit: '12' }); for (const field of ['q', 'category', 'seller', 'minPrice', 'maxPrice']) if (filters[field]) query.set(field, filters[field]); try { const [list, categoryList, sellerList] = await Promise.all([api(`/api/fast-selling?${query}`), api('/api/fast-selling/categories'), api('/api/fast-selling/sellers')]); setProducts(list.data); setMeta(list.meta); setCategories(categoryList.data); setSellers(sellerList.data) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }, filters.q ? 250 : 0); return () => clearTimeout(timer) }, [detailId, filters])
  if (detailId) return <FastDetail id={decodeURIComponent(detailId)} />
  const update = (field, value) => setFilters((current) => ({ ...current, [field]: value, ...(field !== 'page' ? { page: 1 } : {}) }))
  return <><main className="fast-page"><div className="category-breadcrumb shell">Home <span>›</span> Fast Selling</div><section className="fast-hero shell"><p className="eyebrow">Popular right now</p><h1>Fast Selling</h1><p>Discover pieces buyers return to—proven products from verified Indonesian makers.</p></section><section className="fast-catalog shell"><div className="fast-toolbar"><label className="fast-search">⌕<input value={filters.q} onChange={(event) => update('q', event.target.value)} placeholder="Search fast-selling products" /></label><select value={filters.category} onChange={(event) => update('category', event.target.value)}><option value="">All categories</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={filters.seller} onChange={(event) => update('seller', event.target.value)}><option value="">All sellers</option>{sellers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input type="number" min="0" value={filters.minPrice} onChange={(event) => update('minPrice', event.target.value)} placeholder="Min price" /><input type="number" min="0" value={filters.maxPrice} onChange={(event) => update('maxPrice', event.target.value)} placeholder="Max price" /><select value={filters.sort} onChange={(event) => update('sort', event.target.value)}><option value="sales-volume">Sales volume</option><option value="popularity">Popularity</option><option value="newest">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div>{loading && <p className="fast-state">Loading fast-selling products…</p>}{!loading && message && <p className="fast-state fast-state--error">{message}</p>}{!loading && !message && <><p className="category-count">{meta.total} items</p>{products.length ? <div className="category-product-grid">{products.map((product) => <FastCard product={product} key={product.id} />)}</div> : <p className="fast-state">No fast-selling products match these filters.</p>}</>}{meta.pages > 1 && <nav className="saved-pagination"><button disabled={meta.page <= 1} onClick={() => update('page', meta.page - 1)}>← Previous</button><span>Page {meta.page} of {meta.pages}</span><button disabled={meta.page >= meta.pages} onClick={() => update('page', meta.page + 1)}>Next →</button></nav>}</section></main><FastFooter /></>
}
