import { useEffect, useState } from 'react'

const money = (value, currency = 'IDR') => new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value)
const api = async (url) => { const response = await fetch(url); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load flash sales.'); return payload }

function Countdown({ sale }) {
  const [now, setNow] = useState(Date.now())
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer) }, [])
  const target = new Date(sale.status === 'upcoming' ? sale.startTime : sale.endTime).getTime(); const seconds = Math.max(0, Math.floor((target - now) / 1000)); const days = Math.floor(seconds / 86400); const hours = Math.floor(seconds % 86400 / 3600); const minutes = Math.floor(seconds % 3600 / 60); const remainingSeconds = seconds % 60
  return <span className="flash-countdown">{sale.status === 'upcoming' ? 'Starts in' : sale.status === 'expired' ? 'Ended' : 'Ends in'} {sale.status !== 'expired' && `${days}d ${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(remainingSeconds).padStart(2, '0')}`}</span>
}

function ProductCard({ product, saleId }) {
  return <article className="category-product-card flash-product"><a href={`/flash-sales/${saleId}`}><div><img src={product.image} alt={product.title} /><em>-{product.discountPercent}%</em></div><h2>{product.title}</h2><small>{product.seller?.verified ? 'Verified seller' : product.category?.name}</small><span><del>{money(product.originalPrice, product.currency)}</del><strong>{money(product.salePrice, product.currency)}</strong></span><footer><span>{product.remainingStock} remaining</span><span>★ {product.rating}/5</span></footer></a></article>
}

function FlashFooter() { return <footer className="account-footer flash-footer shell"><div className="logo">buyamia</div><p>Buy some comfort. Buy<br />some care.</p><div><small>SHOP</small><span>All Products</span><span>Furniture</span><span>Home Decor</span></div><div><small>ABOUT US</small><span>About Us</span><span>Sustainability</span><span>Sell on Buyamia</span></div><div><small>SUPPORT</small><span>Help Center</span><span>Contact Us</span><span>FAQ</span></div></footer> }

function FlashSaleDetail({ id }) {
  const [sale, setSale] = useState(null); const [message, setMessage] = useState('')
  useEffect(() => { api(`/api/flash-sales/${encodeURIComponent(id)}`).then((payload) => setSale(payload.data)).catch((error) => setMessage(error.message)) }, [id])
  if (!sale) return <main className={`flash-state shell${message ? ' flash-state--error' : ''}`}>{message || 'Loading flash sale…'}</main>
  return <><main className="flash-page"><div className="category-breadcrumb shell"><a href="/flash-sales">Flash Sale</a> <span>›</span> {sale.title}</div><section className="flash-hero shell"><p className="eyebrow">{sale.status === 'upcoming' ? 'Coming soon' : sale.status === 'expired' ? 'Sale ended' : 'Live now'}</p><h1>{sale.title}</h1><p>{sale.description}</p><Countdown sale={sale} /></section><section className="flash-catalog shell"><p className="category-count">{sale.productCount} items</p><div className="category-product-grid">{sale.products.map((product) => <ProductCard product={product} saleId={sale.id} key={product.id} />)}</div></section></main><FlashFooter /></>
}

export default function FlashSalesPage() {
  const detailId = window.location.pathname.match(/^\/flash-sales\/([^/]+)$/)?.[1]
  const [sales, setSales] = useState([]); const [categories, setCategories] = useState([]); const [meta, setMeta] = useState({ page: 1, pages: 1, total: 0 }); const [filters, setFilters] = useState({ q: '', status: 'current', category: '', sort: 'ending-soon', page: 1 }); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  useEffect(() => { if (detailId) return; const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); setMessage(''); const query = new URLSearchParams({ status: filters.status, sort: filters.sort, page: String(filters.page), limit: '8' }); if (filters.q) query.set('q', filters.q); if (filters.category) query.set('category', filters.category); try { const [list, categoryList] = await Promise.all([api(`/api/flash-sales?${query}`), api('/api/flash-sales/categories')]); setSales(list.data); setMeta(list.meta); setCategories(categoryList.data) } catch (error) { if (error.name !== 'AbortError') setMessage(error.message) } finally { setLoading(false) } }, filters.q ? 250 : 0); return () => { clearTimeout(timer); controller.abort() } }, [detailId, filters])
  if (detailId) return <FlashSaleDetail id={decodeURIComponent(detailId)} />
  const update = (field, value) => setFilters((current) => ({ ...current, [field]: value, ...(field !== 'page' ? { page: 1 } : {}) }))
  return <><main className="flash-page"><div className="category-breadcrumb shell">Home <span>›</span> Flash Sale</div><section className="flash-hero shell"><p className="eyebrow">Limited-time Buyamia offers</p><h1>Flash Sale</h1><p>Discover active offers and preview what is coming next from verified Indonesian makers.</p></section><section className="flash-catalog shell"><div className="flash-toolbar"><label className="flash-search">⌕<input value={filters.q} onChange={(event) => update('q', event.target.value)} placeholder="Search flash sales" /></label><select value={filters.status} onChange={(event) => update('status', event.target.value)}><option value="current">Active &amp; upcoming</option><option value="active">Active</option><option value="upcoming">Upcoming</option><option value="expired">History</option></select><select value={filters.category} onChange={(event) => update('category', event.target.value)}><option value="">All categories</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={filters.sort} onChange={(event) => update('sort', event.target.value)}><option value="ending-soon">Ending soon</option><option value="starting-soon">Starting soon</option><option value="discount-high">Biggest discount</option><option value="newest">Newest</option></select></div>{loading && <p className="flash-state">Loading flash sales…</p>}{!loading && message && <p className="flash-state flash-state--error">{message}</p>}{!loading && !message && !sales.length && <p className="flash-state">No flash sales match these filters.</p>}{!loading && !message && sales.map((sale) => <section className="flash-sale" key={sale.id}><header><div><p className="eyebrow">{sale.status}</p><h2><a href={`/flash-sales/${sale.id}`}>{sale.title}</a></h2><p>{sale.description}</p></div><Countdown sale={sale} /></header><div className="category-product-grid">{sale.products.map((product) => <ProductCard product={product} saleId={sale.id} key={product.id} />)}</div></section>)}{meta.pages > 1 && <nav className="saved-pagination"><button disabled={meta.page <= 1} onClick={() => update('page', meta.page - 1)}>← Previous</button><span>Page {meta.page} of {meta.pages}</span><button disabled={meta.page >= meta.pages} onClick={() => update('page', meta.page + 1)}>Next →</button></nav>}</section></main><FlashFooter /></>
}
