import { useEffect, useState } from 'react'

const formatMoney = (value, currency) => new Intl.NumberFormat('en-US', { style: 'currency', currency: currency || 'IDR', maximumFractionDigits: 0 }).format(value || 0)

export default function OrdersPage() {
  const [orders, setOrders] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [filter, setFilter] = useState('')
  async function load(status = '') { const response = await fetch(`/api/orders?limit=20${status ? `&status=${encodeURIComponent(status)}` : ''}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load orders.'); setOrders(payload.data) }
  useEffect(() => { load().catch((error) => setMessage(error.message)).finally(() => setLoading(false)) }, [])
  async function select(id) { try { const response = await fetch(`/api/orders/${id}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load order details.'); setSelected(payload.data) } catch (error) { setMessage(error.message) } }
  async function changeFilter(value) { setFilter(value); setLoading(true); try { await load(value) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  return <main className="orders-page shell"><section className="orders-page__head"><p className="eyebrow">My Account</p><h1>Your <em>Orders</em></h1><p>Review your orders, delivery progress, and payment details.</p></section><div className="orders-toolbar"><label>Status<select value={filter} onChange={(event) => changeFilter(event.target.value)}><option value="">All orders</option><option>Pending</option><option>Confirmed</option><option>Processing</option><option>Shipped</option><option>Out for Delivery</option><option>Delivered</option><option>Cancelled</option><option>Refunded</option></select></label></div><div className="orders-layout"><section className="orders-list"><h2>Order history</h2>{loading && <p>Loading orders…</p>}{!loading && !orders.length && <p>No orders found.</p>}{orders.map((order) => <button type="button" className={selected?.id === order.id ? 'is-selected' : ''} onClick={() => select(order.id)} key={order.id}><span><small>{order.status}</small><strong>{order.orderNumber}</strong><em>{new Date(order.createdAt).toLocaleDateString()}</em></span><b>{formatMoney(order.total, order.currency)}</b></button>)}</section><section className="order-details">{!selected && <p>Select an order to see its details.</p>}{selected && <><header><div><small>{selected.status}</small><h2>{selected.orderNumber}</h2><p>Placed {new Date(selected.createdAt).toLocaleDateString()}</p></div><strong>{formatMoney(selected.total, selected.currency)}</strong></header><div className="order-items">{selected.items.map((item) => <article key={item.productId}><img src={item.product?.image} alt="" /><span><strong>{item.product?.title || 'Product'}</strong><small>Quantity {item.quantity}</small></span><b>{formatMoney(item.unitPrice * item.quantity, selected.currency)}</b></article>)}</div><div className="order-detail-grid"><section><h3>Delivery</h3><p>{selected.shipping?.carrier || 'Shipping to be confirmed'}<br />{selected.trackingNumber || 'Tracking pending'}<br />{selected.deliveryEstimate ? `Estimated ${selected.deliveryEstimate}` : ''}</p></section><section><h3>Payment</h3><p>{selected.payment?.method || 'Payment pending'}<br />{selected.invoiceReference || 'Invoice pending'}</p></section></div><section className="order-timeline"><h3>Order timeline</h3>{selected.timeline.map((entry) => <p key={`${entry.status}-${entry.at}`}><span />{entry.status}<small>{new Date(entry.at).toLocaleDateString()}</small></p>)}</section><footer><span>Subtotal <b>{formatMoney(selected.subtotal, selected.currency)}</b></span><span>Shipping <b>{formatMoney(selected.shippingCost, selected.currency)}</b></span><span>Taxes <b>{formatMoney(selected.taxes, selected.currency)}</b></span><strong>Total <b>{formatMoney(selected.total, selected.currency)}</b></strong></footer></>}</section></div>{message && <p className="orders-message">{message}</p>}</main>
}
