import { useEffect, useState } from 'react'

const money = (value, currency = 'IDR') => new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value)
const api = async (url) => { const response = await fetch(url); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load seller promotions.'); return payload }

function PromoFooter() { return <footer className="account-footer promo-footer shell"><div className="logo">buyamia</div><p>Buy some comfort. Buy<br />some care.</p><div><small>SHOP</small><span>All Products</span><span>Furniture</span><span>Home Decor</span></div><div><small>ABOUT US</small><span>About Us</span><span>Sustainability</span><span>Sell on Buyamia</span></div><div><small>SUPPORT</small><span>Help Center</span><span>Contact Us</span><span>FAQ</span></div></footer> }

function PromoCard({ promotion }) {
  return <article className="promo-card"><a href={`/seller-promotions/${promotion.id}`}><div className="promo-card__media"><img src={promotion.image} alt={promotion.title} /><span>-{promotion.discountPercent}%</span>{promotion.featured && <em>Featured</em>}</div><header><img src={promotion.seller.avatar} alt="" /><span><small>{promotion.seller.verified ? 'Verified seller' : promotion.category.name}</small><strong>{promotion.seller.name}</strong></span></header><h2>{promotion.title}</h2><p>{promotion.description}</p><div className="promo-price"><del>{money(promotion.originalPrice, promotion.product?.currency)}</del><strong>{money(promotion.discountedPrice, promotion.product?.currency)}</strong></div><footer><span>{promotion.category.name}</span><span>{promotion.status}</span></footer></a></article>
}

function PromoDetail({ id }) {
  const [promotion, setPromotion] = useState(null); const [message, setMessage] = useState('')
  useEffect(() => { api(`/api/sellers/promotions/${encodeURIComponent(id)}`).then((payload) => setPromotion(payload.data)).catch((error) => setMessage(error.message)) }, [id])
  if (!promotion) return <main className={`promo-state shell${message ? ' promo-state--error' : ''}`}>{message || 'Loading promotion…'}</main>
  return <><main className="promo-detail shell"><div className="category-breadcrumb"><a href="/seller-promotions">Seller&apos;s Promo</a> <span>›</span> {promotion.title}</div><div><section><img src={promotion.image} alt={promotion.title} /></section><section><header><img src={promotion.seller.avatar} alt="" /><span><p className="eyebrow">{promotion.seller.verified ? 'Verified seller' : 'Buyamia seller'}</p><strong>{promotion.seller.name}</strong><small>{promotion.seller.location}</small></span></header><h1>{promotion.title}</h1><p>{promotion.description}</p><div className="promo-detail__price"><del>{money(promotion.originalPrice, promotion.product?.currency)}</del><strong>{money(promotion.discountedPrice, promotion.product?.currency)}</strong><em>Save {promotion.discountPercent}%</em></div><dl><div><dt>Status</dt><dd>{promotion.status}</dd></div><div><dt>Category</dt><dd>{promotion.category.name}</dd></div><div><dt>Valid from</dt><dd>{new Date(promotion.startTime).toLocaleDateString()}</dd></div><div><dt>Valid until</dt><dd>{new Date(promotion.endTime).toLocaleDateString()}</dd></div><div><dt>Availability</dt><dd>{promotion.availability ? 'Available' : 'Unavailable'}</dd></div></dl>{promotion.product && <a className="btn btn-accent" href={`/cart?product=${encodeURIComponent(promotion.product.id)}`}>Shop this offer</a>}</section></div></main><PromoFooter /></>
}

export default function SellerPromotionsPage() {
  const detailId = window.location.pathname.match(/^\/seller-promotions\/([^/]+)$/)?.[1]
  const [promotions, setPromotions] = useState([]); const [categories, setCategories] = useState([]); const [sellers, setSellers] = useState([]); const [meta, setMeta] = useState({ page: 1, pages: 1, total: 0 }); const [filters, setFilters] = useState({ q: '', category: '', seller: '', status: 'active', sort: 'newest', page: 1 }); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  useEffect(() => { if (detailId) return; const timer = setTimeout(async () => { setLoading(true); setMessage(''); const query = new URLSearchParams({ status: filters.status, sort: filters.sort, page: String(filters.page), limit: '12' }); for (const field of ['q', 'category', 'seller']) if (filters[field]) query.set(field, filters[field]); try { const [list, categoryList, sellerList] = await Promise.all([api(`/api/sellers/promotions?${query}`), api('/api/sellers/promotions/categories'), api('/api/sellers/promotions/sellers')]); setPromotions(list.data); setMeta(list.meta); setCategories(categoryList.data); setSellers(sellerList.data) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }, filters.q ? 250 : 0); return () => clearTimeout(timer) }, [detailId, filters])
  if (detailId) return <PromoDetail id={decodeURIComponent(detailId)} />
  const update = (field, value) => setFilters((current) => ({ ...current, [field]: value, ...(field !== 'page' ? { page: 1 } : {}) }))
  return <><main className="promotions-page"><div className="category-breadcrumb shell">Home <span>›</span> Seller&apos;s Promo</div><section className="promotions-hero shell"><p className="eyebrow">Offers from Buyamia sellers</p><h1>Seller&apos;s Promo</h1><p>Discover limited-time offers directly from verified Indonesian makers and marketplace partners.</p></section><section className="promotions-catalog shell"><div className="promotions-toolbar"><label>⌕<input value={filters.q} onChange={(event) => update('q', event.target.value)} placeholder="Search promotions" /></label><select value={filters.category} onChange={(event) => update('category', event.target.value)}><option value="">All categories</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={filters.seller} onChange={(event) => update('seller', event.target.value)}><option value="">All sellers</option>{sellers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={filters.status} onChange={(event) => update('status', event.target.value)}><option value="active">Active</option><option value="upcoming">Upcoming</option><option value="expired">Expired</option><option value="all">All promotions</option></select><select value={filters.sort} onChange={(event) => update('sort', event.target.value)}><option value="newest">Newest</option><option value="ending-soon">Ending soon</option><option value="discount-high">Biggest discount</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></div>{loading && <p className="promo-state">Loading seller promotions…</p>}{!loading && message && <p className="promo-state promo-state--error">{message}</p>}{!loading && !message && <><p className="category-count">{meta.total} promotions</p>{promotions.length ? <div className="promotions-grid">{promotions.map((promotion) => <PromoCard promotion={promotion} key={promotion.id} />)}</div> : <p className="promo-state">No seller promotions match these filters.</p>}</>}{meta.pages > 1 && <nav className="saved-pagination"><button disabled={meta.page <= 1} onClick={() => update('page', meta.page - 1)}>← Previous</button><span>Page {meta.page} of {meta.pages}</span><button disabled={meta.page >= meta.pages} onClick={() => update('page', meta.page + 1)}>Next →</button></nav>}</section></main><PromoFooter /></>
}
