import { useEffect, useState } from 'react'

function money(value, currency) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: currency || 'IDR', maximumFractionDigits: 0 }).format(value || 0) }

export default function SourcePage() {
  const [item, setItem] = useState(null); const [image, setImage] = useState(0); const [quantity, setQuantity] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  useEffect(() => { const controller = new AbortController(); fetch('/api/source?limit=1', { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load sourced item.'); if (!payload.data.length) throw new Error('No sourced items are available.'); return fetch(`/api/source/${payload.data[0].id}`, { signal: controller.signal }) }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to load sourced item.'); setItem(payload.data) }).catch((error) => { if (error.name !== 'AbortError') setMessage(error.message) }).finally(() => setLoading(false)); return () => controller.abort() }, [])
  if (loading) return <main className="source-page shell"><p className="source-state">Loading sourced item…</p></main>
  if (message || !item) return <main className="source-page shell"><p className="source-state source-state--error">{message || 'Sourced item unavailable.'}</p></main>
  return <main className="source-page shell"><div className="source-breadcrumb">Home <span>›</span> {item.category} <span>›</span> {item.title}</div><section className="source-top"><div className="source-gallery"><img className="source-main-image" src={item.images[image]} alt={item.title} /><div>{item.images.map((url, index) => <button type="button" className={index === image ? 'is-active' : ''} onClick={() => setImage(index)} key={url}><img src={url} alt="" /></button>)}</div></div><section className="source-summary"><h1>{item.title}</h1><div className="source-price"><small>Estimated price</small><em>{item.sourceLabel}</em><strong>{money(item.product.price, item.product.currency)}</strong></div><p className="source-notice">{item.description}</p><label className="source-quantity"><select value={quantity} onChange={(event) => setQuantity(event.target.value)}><option value="">Select Quantity</option>{[item.moq, item.moq * 2, item.moq * 5].map((amount) => <option value={amount} key={amount}>{amount} pcs</option>)}</select></label><button type="button" className="source-cart" onClick={() => setMessage(quantity ? `Sourcing request prepared for ${quantity} pcs.` : `Select a quantity of at least ${item.moq} pcs.`)}>Add to cart <span>↗</span></button>{message && <p className="source-action-message">{message}</p>}<div className="source-badge">{item.sourceLabel} <span>Shop on {item.sourceWebsite}</span></div><section className="source-details"><h2>Product details</h2><dl><dt>Minimum Order</dt><dd>{item.moq} pcs</dd><dt>Shipping</dt><dd>{item.shipping.join(' · ')}</dd><dt>Customization</dt><dd>{item.customization ? 'Yes' : 'No'}</dd><dt>Warranty</dt><dd>{item.warranty ? 'Yes' : 'No'}</dd><dt>Material</dt><dd>{item.material}</dd><dt>Dimensions</dt><dd>{item.dimensions}</dd><dt>Weight</dt><dd>{item.weight}</dd></dl></section></section></section><section className="source-general"><h2>General Information</h2><h2>Product Details</h2><h2>Shipping Information</h2><p>{item.description}</p></section><section className="source-related"><p className="eyebrow">Related Products</p><h2>You might also like</h2><div>{item.relatedProducts.map((product) => <article key={product.id}><img src={product.image} alt={product.title} /><strong>{product.title}</strong><small>Estimated price</small><b>{money(product.price, product.currency)}</b></article>)}</div></section></main>
}
