import { useEffect, useState } from 'react'

function price(product) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: product.currency || 'IDR', maximumFractionDigits: 0 }).format(product.price || 0) }

export default function WishlistPage() {
  const [items, setItems] = useState([]); const [count, setCount] = useState(0); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  async function load() { setLoading(true); setMessage(''); try { const [wishlistResponse, countResponse] = await Promise.all([fetch('/api/account/wishlist?limit=100', { credentials: 'include' }), fetch('/api/account/wishlist/count', { credentials: 'include' })]); const [wishlist, countPayload] = await Promise.all([wishlistResponse.json(), countResponse.json()]); if (!wishlistResponse.ok || !countResponse.ok) throw new Error(wishlist.error?.message || countPayload.error?.message || 'Unable to load your wishlist.'); setItems(wishlist.data); setCount(countPayload.data.count) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function remove(id) { setMessage(''); try { const response = await fetch(`/api/account/wishlist/${encodeURIComponent(id)}`, { method: 'DELETE', credentials: 'include' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to remove this item.'); setItems((current) => current.filter((item) => item.id !== id)); setCount((current) => Math.max(0, current - 1)) } catch (error) { setMessage(error.message) } }
  async function clear() { setMessage(''); try { const response = await fetch('/api/account/wishlist', { method: 'DELETE', credentials: 'include' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Unable to clear your wishlist.'); setItems([]); setCount(0) } catch (error) { setMessage(error.message) } }
  return <main className="history-page shell"><header className="history-page__head"><div><p className="eyebrow">My Account</p><h1>Your <em>Wishlist</em></h1><p>{count ? `${count} saved item${count === 1 ? '' : 's'}` : 'Save products you would like to revisit.'}</p></div>{Boolean(items.length) && <button type="button" className="history-clear" onClick={clear}>Clear wishlist</button>}</header>{loading && <p className="history-state">Loading wishlist…</p>}{!loading && message && <p className="history-state history-state--error">{message}</p>}{!loading && !message && !items.length && <p className="history-state">Your wishlist is empty.</p>}{!loading && !message && <section className="history-group"><div>{items.map((item) => <article className="history-item" key={item.id}><a href={`/products/${item.product.id}`} className="history-item__link"><img src={item.product.image || '/assets/product-thumb.png'} alt="" /><span><small>{item.product.categoryId || 'Product'}</small><strong>{item.product.title}</strong><em>{price(item.product)}</em></span></a><button type="button" aria-label={`Remove ${item.product.title} from wishlist`} onClick={() => remove(item.id)}>Remove</button></article>)}</div></section>}</main>
}
